### ISSUE TITLE
[Feature Request] Restore manga list state when navigating back from Manga Details

### ISSUE THREAD

**Issue by rzmeu** [Suwayomi/Tachidesk-WebUI#178] opened 2022-07-03 17:17 UTC
## What feature should be added to Tachidesk?
On manga list page when navigating back, page should not be reloaded, scrolling position should not be lost.

##  Why/Project's Benefit/Existing Problem
It's very frustrating to scroll from the start every time we click on a manga and then on back button.

Steps to reproduce:
1. Select a source by clicking on "Browse" or "Latest" button
2. Scroll down several mangas
4. Click on a manga
5. Press the back button or browser back button
6. The page is reloaded, scrolling position is lost!

The page should not be reloaded, it should return to the previous scrolling position so we can continue scrolling from where we left.

**Comment by AriaMoradi** [comment] 2022-07-04 20:24
duplicate of #7

**Closed by AriaMoradi** 2022-07-04 20:24 UTC
Labels: enhancement
